### ISSUE TITLE
./tuner/run_tuner.sh error

### ISSUE THREAD

**Issue by Picrew** [NVlabs/AutoDMP#10]
- CUDA-11.3
- torch 1.12.1 with 11.3
run ./tuner/run_tuner.sh meet error 
`(autodmp) ljj@ljj-System-Product-Name:~/ljj/AutoDMP$ sudo -E ./tuner/run_tuner.sh 1 1 test/nvdla_nangate45_51/configspace.json test/nvdla_nangate45_51/NV_NVDLA_partition_c.aux test/nvdla_nangate45_51/nvdla_ppa.json \"\" 20 2 0 0 10 ./tuner test/nvdla_nangate45_51/mobohb_log
Parameters: 1 1 test/nvdla_nangate45_51/configspace.json test/nvdla_nangate45_51/NV_NVDLA_partition_c.aux test/nvdla_nangate45_51/nvdla_ppa.json "" 20 2 0 0 10 ./tuner test/nvdla_nangate45_51/mobohb_log
# Parameters: 190
(autodmp) ljj@ljj-System-Product-Name:~/ljj/AutoDMP$ Traceback (most recent call last):
  File "./tuner/tuner_train.py", line 36, in <module>
    from tuner_worker import AutoDMPWorker
  File "/home/ljj/ljj/AutoDMP/tuner/tuner_worker.py", line 28, in <module>
    from dreamplace.Placer import PlacementEngine
  File "/home/ljj/ljj/AutoDMP/dreamplace/Placer.py", line 42, in <module>
Traceback (most recent call last):
  File "./tuner/tuner_train.py", line 36, in <module>
    import dreamplace.NonLinearPlace as NonLinearPlace
  File "/home/ljj/ljj/AutoDMP/dreamplace/NonLinearPlace.py", line 39, in <module>
    import dreamplace.BasicPlace as BasicPlace
  File "/home/ljj/ljj/AutoDMP/dreamplace/BasicPlace.py", line 48, in <module>
    from tuner_worker import AutoDMPWorker
    import dreamplace.ops.independent_set_matching.independent_set_matching as independent_set_matching
  File "/home/ljj/ljj/AutoDMP/tuner/tuner_worker.py", line 28, in <module>
  File "/home/ljj/ljj/AutoDMP/dreamplace/ops/independent_set_matching/independent_set_matching.py", line 32, in <module>
    import dreamplace.ops.independent_set_matching.independent_set_matching_cuda as independent_set_matching_cuda
ImportError: /home/ljj/ljj/AutoDMP/dreamplace/ops/independent_set_matching/independent_set_matching_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: curandCreateGenerator
    from dreamplace.Placer import PlacementEngine
  File "/home/ljj/ljj/AutoDMP/dreamplace/Placer.py", line 42, in <module>
    import dreamplace.NonLinearPlace as NonLinearPlace
  File "/home/ljj/ljj/AutoDMP/dreamplace/NonLinearPlace.py", line 39, in <module>
    import dreamplace.BasicPlace as BasicPlace
  File "/home/ljj/ljj/AutoDMP/dreamplace/BasicPlace.py", line 48, in <module>
    import dreamplace.ops.independent_set_matching.independent_set_matching as independent_set_matching
  File "/home/ljj/ljj/AutoDMP/dreamplace/ops/independent_set_matching/independent_set_matching.py", line 32, in <module>
    import dreamplace.ops.independent_set_matching.independent_set_matching_cuda as independent_set_matching_cuda
ImportError: /home/ljj/ljj/AutoDMP/dreamplace/ops/independent_set_matching/independent_set_matching_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: curandCreateGenerator
Traceback (most recent call last):
  File "./tuner/tuner_train.py", line 36, in <module>
    from tuner_worker import AutoDMPWorker
  File "/home/ljj/ljj/AutoDMP/tuner/tuner_worker.py", line 28, in <module>
    from dreamplace.Placer import PlacementEngine
  File "/home/ljj/ljj/AutoDMP/dreamplace/Placer.py", line 42, in <module>
    import dreamplace.NonLinearPlace as NonLinearPlace
  File "/home/ljj/ljj/AutoDMP/dreamplace/NonLinearPlace.py", line 39, in <module>
    import dreamplace.BasicPlace as BasicPlace
  File "/home/ljj/ljj/AutoDMP/dreamplace/BasicPlace.py", line 48, in <module>
    import dreamplace.ops.independent_set_matching.independent_set_matching as independent_set_matching
  File "/home/ljj/ljj/AutoDMP/dreamplace/ops/independent_set_matching/independent_set_matching.py", line 32, in <module>
    import dreamplace.ops.independent_set_matching.independent_set_matching_cuda as independent_set_matching_cuda
ImportError: /home/ljj/ljj/AutoDMP/dreamplace/ops/independent_set_matching/independent_set_matching_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: curandCreateGenerator
`
How to fix it

**Comment by neema-m** [comment]
You are most likely using a later version of CUDA that is not compatible with Dreamplace. Try downgrading CUDA to an older version or, even better, update Dreamplace to newest release which should support CUDA 10/11.
