### ISSUE TITLE
KeyError while running the initial test

### ISSUE THREAD

**Issue by dkrevana** [NVlabs/AutoDMP#7]
Hello,

When I run the following command in the AutoDMP docker env.
```
./tuner/run_tuner.sh 1 1 test/nvdla_nangate45_51/configspace.json test/nvdla_nangate45_51/NV_NVDLA_partition_c.aux test/nvdla_nangate45_51/nvdla_ppa.json \"\" 20 2 0 0 10 ./tuner test/nvdla_nangate45_51/mobohb_log
```

The master process runs into a key error as shown below

```
root@3504aa7e631b:/AutoDMP# Starting master process
Master args: Namespace(cfgSearchFile='test/nvdla_nangate45_51/configspace.json', congestion_ratio=0.5, density_ratio=0.5, gpu_pool=[-1], log_dir='test/nvdla_nangate45_51/mobohb_log/NV_NVDLA_partition_c', max_budget=1, min_budget=1, min_points_in_model=10, multiobj=True, n_iterations=20, n_samples=64, n_workers=2, num_pareto=5, run_args={'aux_input': 'test/nvdla_nangate45_51/NV_NVDLA_partition_c.aux'}, run_id='0', worker=False, worker_id=0)
Traceback (most recent call last):
  File "./tuner/tuner_train.py", line 167, in <module>
    configspace=AutoDMPWorker.get_configspace(args.cfgSearchFile),
  File "/AutoDMP/tuner/tuner_worker.py", line 173, in get_configspace
    cs = CS_JSON.read(f.read())
  File "/opt/conda/lib/python3.8/site-packages/ConfigSpace/read_and_write/json.py", line 444, in read
    _construct_hyperparameter(
  File "/opt/conda/lib/python3.8/site-packages/ConfigSpace/read_and_write/json.py", line 490, in _construct_hyperparameter
    q=hyperparameter["q"],
KeyError: 'q'
```

Any pointers on how to get around this issue?

**Comment by dkrevana** [comment]
Downgrading the ConfigSpace python package to 0.6.1 from 0.7.1 resolved the issue.

**Comment by IshraqAtUCF** [comment]
Did you face any issues running afterwards? @dkrevana
